### ISSUE TITLE
Cards edited on AnkiDroid do not change

### ISSUE THREAD

**Issue by Fun-Ken** [RisingOrange/anki-enhanced-cloze#10]
Cards that use this **note type**: Enhanced Cloze 2.1 v2, seem to have problems if modified on **AnkiDroid**. Cards can be modified, but these modifications are not then implemented. 

**Example**: On Anki (desktop or android) I make a card with Enhanced Cloze 2.1 v2 as note type. Then I want to edit some words on AnkiDroid. If I edit some of these words on the next review these modifications are not implemented and the card remains as before the edit.

**This doesn't happen on Anki Desktop**. If I use the edit option on Anki Desktop, after I've modified the card on AnkiDroid, and then I save without making any new changes, the card updates and finally I see the modification. On AnkiDroid this addon seems pretty buggy.

**AnkiDroid version**: 2.15.6

**Comment by gustavosmendes** [comment]
You need to open anki desktop and click "update enhanced clozes" on browser. 
![image](https://user-images.githubusercontent.com/87918773/134392446-c1c4013e-a85e-4d60-8d51-b5dfab73f51a.png)

**Comment by gustavosmendes** [comment]
But you can upgrade your notes on ankidroid if you check properly the data field in ankidroid.

**Comment by Fun-Ken** [comment]
Okay I tried to edit a card from the data field and it works but why is set up like this?

**Comment by RisingOrange** [comment]
It is set up like this because I couldn't come up with a better way to make anki generate a variable amount of cards for a single note while adding features to clozes. Maybe there could be a better solution.
