### ISSUE TITLE
Doesn't show image

### ISSUE THREAD

**Issue by pentabi** [RisingOrange/anki-enhanced-cloze#11]
On my Mac, when I create cards I can see my pasted image on the edit section but when I'm actually studying it doesn't show the image. Is there a way to fix this? Thank you in advance

**Comment by pentabi** [comment]
btw my Anki is Version ⁨2.1.46

**Comment by gustavosmendes** [comment]
update your addon. This has been resolved in the latest versions.

**Comment by RisingOrange** [comment]
@gustavosmendes is right, the image problem should be fixed since the last update to the add-on. Try checking for updates (Tools -> Addons -> Check for updates)

**Comment by pentabi** [comment]
I have the latest version and this problem still occurs.

**Comment by RisingOrange** [comment]
Please try creating a new note with an image on it and see if it works. Notes with jmages that were created before the update won't work.

Are you reviewing the card on the Mac or on mobile? 
Is there a small "missing image" icon where the image should be?

**Comment by pentabi** [comment]
I'm reviewing on a mac and there is a missing image icon where the image should be. This problem only occurs when the image is in the "content" section. 

<script type="text/javascript">data={"parts": [["<img src=%5C%22Screen Shot 2021-09-30 at 8.29.15 AM.png\"><br>central dogma can be compared to each of these<br>recipe- <span class=\"", 1], ["\" index=\"0\" show-state=\"hint\" cloze-id=\"c1\"></span><br>copied on index card- <span class=\"", 1], ["\" index=\"1\" show-state=\"hint\" cloze-id=\"c1\"></span><br>using right indigredients- <span class=\"", 1], ["\" index=\"2\" show-state=\"hint\" cloze-id=\"c1\"></span><br>pizza- <span class=\"", 1], ["\" index=\"3\" show-state=\"hint\" cloze-id=\"c1\"></span><span class=\"", 1], ["\" index=\"4\" show-state=\"hint\" cloze-id=\"c1\"></span>", null]], "answers": ["DNA", "mRNA", "Amino Acids", "Proteins", "<img src=%5C%22Screen Shot 2021-09-30 at 8.47.30 AM.png\">"], "hints": ["", "", "", "", ""]}</script>

I clicked on check on updates and it said that no update is available. Thank you for your time.

**Comment by RisingOrange** [comment]
From what you sent me it seems like doing this should help. Please check if it workds after doing this:

![update_enhanced_clozes](https://user-images.githubusercontent.com/31575114/135464862-350f2d91-67d7-4220-bbca-cbaa86d73c09.gif)

(This refreshes the text in the data field of all Enhanced Cloze notes.)

**Comment by pentabi** [comment]
I tried everything and it still doesn't work. I made a new card with new photos (both jpeg and png) and it still does not work. This problem specifically occurs in the content section of the Anki.

**Comment by RisingOrange** [comment]
I just updated the add-on and images should work reliably now. Sorry that this took so long!

**Comment by pentabi** [comment]
It works now!!! This is absolutely life-changing!! Thank you so much for fixing it I appreciate it!
Also, I'm a Biology major but planning to switch majors to CS because I have some interest in coding. This might be off-topic but I thought this is one example of how coding really can help and change people's lives for the better. But again thanks!
