### ISSUE TITLE
No button 'i' on ipad

### ISSUE THREAD

**Issue by WolfPackStatMathieu** [RisingOrange/anki-enhanced-cloze#12]
Hello,

First, I think your work is really great! I'm looking for a way of learning maths exercices with mathjax and revealing clozes incrementally, with all clozes of the same height. (Contrary to the Anking card "Cloze one by one", where the entire sentence is hidden under a (too small) box. 
So your solution is really convenient. 
But on ipad, this doesn't work, I think it's because there is no "touch event" like on desktop with the 'i'. 
Do you think it's possible to fix it ? 

Thank you,

**Comment by WolfPackStatMathieu** [comment]
There is a problem. I've updated and the notetype doesn't work anymore. 
I tried to reinstall the addon (and suppressed the notetype) but now I can't find the notetype.
And it seems there is another problem  about it in the issues.

**Comment by RisingOrange** [comment]
What did happen before the update when you touched the clozes on the ipad? Did it also reveal every cloze at once or did something else happen? I unfortunately have no iOS device to test it on currently.

**Comment by RisingOrange** [comment]
Please try this: 
1. Update the add-on again
2. See if it works after a restart, if not stop here
3. Go to Tools -> Preferences, Check the "on next sync, force changes in one direction"
4. Synchronize
5. Now synchronize on your ipad and choose the option for getting the collection from ankiweb
6. Try if clozes now work on the ipad

**Comment by WolfPackStatMathieu** [comment]
> What did happen before the update when you touched the clozes on the ipad? Did it also reveal every cloze at once or did something else happen? I unfortunately have no iOS device to test it on currently.

It revealed every cloze at once.

**Comment by WolfPackStatMathieu** [comment]
> Please try this:
> 
> 1. Update the add-on again
> 2. See if it works after a restart, if not stop here
> 3. Go to Tools -> Preferences, Check the "on next sync, force changes in one direction"
> 4. Synchronize
> 5. Now synchronize on your ipad and choose the option for getting the collection from ankiweb
> 6. Try if clozes now work on the ipad

It works ! Thanks !
But it's a bit impractical. If your finger press too much, or miss it, everything is revealed at once. I'm trying to understand what is the good level of finger pressure.

**Comment by WolfPackStatMathieu** [comment]
:) That's good enough to work with now !
Obviously, touching the screen to reveal answers requires deactivating other touches that reveal the answer. But as I need to touch the screen to answer other faster cards (I don't want to have to reveal the "answer button" by making two touches), I only activated the top right area of the screen to reveal the answer. 
The card is stable enough to work with now. 

Thank you

**Comment by RisingOrange** [comment]
Great! After uploading the last update I noticed that revealing clozes on the back of the card stopped working. That's why I uploaded another update. 
You may have to force an upload to update the note type on your iPad again.
