### ISSUE TITLE
All of my cards with the "Enhanced Cloze for Anki 21" card type shows the message "This is an example […]" in the Question field.

### ISSUE THREAD

**Issue by BellaMed** [RisingOrange/anki-enhanced-cloze#14]
<img width="958" alt="Screen Shot 2021-10-10 at 10 40 15 AM" src="https://user-images.githubusercontent.com/92262098/136700465-0c05d55f-1ff1-47ae-a427-5bf4f2062a49.png">

<img width="353" alt="Screen Shot 2021-10-10 at 10 40 26 AM" src="https://user-images.githubusercontent.com/92262098/136700480-0e3b2793-788c-45fc-bb3f-63b181d068de.png">

When in preview mode

Front:
<img width="401" alt="Screen Shot 2021-10-10 at 10 42 40 AM" src="https://user-images.githubusercontent.com/92262098/136700541-c4c74163-cf82-4d31-ae55-237005290e2c.png">

Back:
<img width="430" alt="Screen Shot 2021-10-10 at 10 42 31 AM" src="https://user-images.githubusercontent.com/92262098/136700535-68946dec-a609-434b-98dd-c6b5b20501a2.png">

**Comment by BellaMed** [comment]
Front Template: 

<div id="card-body">
    <div id="main-section" class="content">
        
        <span id="dummy-clozes" style="display: none;">
            {{cloze:Cloze1}}
            {{cloze:Cloze2}}
            {{cloze:Cloze3}}
            {{cloze:Cloze4}}
            {{cloze:Cloze5}}
            {{cloze:Cloze6}}
            {{cloze:Cloze7}}
            {{cloze:Cloze8}}
            {{cloze:Cloze9}}
            {{cloze:Cloze10}}
            {{cloze:Cloze11}}
            {{cloze:Cloze12}}
            {{cloze:Cloze13}}
            {{cloze:Cloze14}}
            {{cloze:Cloze15}}
            {{cloze:Cloze16}}
            {{cloze:Cloze17}}
            {{cloze:Cloze18}}
            {{cloze:Cloze19}}
            {{cloze:Cloze20}}
            {{cloze:Cloze21}}
            {{cloze:Cloze22}}
            {{cloze:Cloze23}}
            {{cloze:Cloze24}}
            {{cloze:Cloze25}}
            {{cloze:Cloze26}}
            {{cloze:Cloze27}}
            {{cloze:Cloze28}}
            {{cloze:Cloze29}}
            {{cloze:Cloze30}}
            {{cloze:Cloze31}}
            {{cloze:Cloze32}}
            {{cloze:Cloze33}}
            {{cloze:Cloze34}}
            {{cloze:Cloze35}}
            {{cloze:Cloze36}}
            {{cloze:Cloze37}}
            {{cloze:Cloze38}}
            {{cloze:Cloze39}}
            {{cloze:Cloze40}}
            {{cloze:Cloze41}}
            {{cloze:Cloze42}}
            {{cloze:Cloze43}}
            {{cloze:Cloze44}}
            {{cloze:Cloze45}}
            {{cloze:Cloze46}}
            {{cloze:Cloze47}}
            {{cloze:Cloze48}}
            {{cloze:Cloze49}}
            {{cloze:Cloze50}}
        </span>
        <span id="data" style="display: none;">
            {{data}}
        </span>
        
        <span id="enhanced-clozes">
            This is an example <span class="genuine-cloze" index="0" show-state="hint"cloze-id="c1">&nbsp;&nbsp;[&nbsp;&nbsp;&nbsp;&nbsp;]&nbsp;&nbsp;</span>
        </span>
    </div>
    <br>
    <br>
    <hr>
    <br>
    <p class="" style="margin: 5.5px;"></p>


<div>
    
    {{#Note}}
    <div id="note-section">
        <div id="note-header" class="header header-red" onclick="showNextElement(this)">
            Note
        </div>
        <div id="note" class="content" style="display:none">
            {{Note}}
        </div>
    </div>
    <br> 
    <p class="" style="margin: 5.5px;"></p>
    {{/Note}}

    {{#Mnemonics}}
    <div id="mnemonics-section">
        <div id="mnemonics-header" class="header header-green" onclick="showNextElement(this)">
            Mnemonics
        </div>
        <div id="mnemonics" class="content" style="display:none">
            {{Mnemonics}}
        </div>
    </div>
    <br> 
    <p class="" style="margin: 5.5px;"></p>
    {{/Mnemonics}}

    {{#Extra}}
    <div id="extra-section">
        <div id="extra-header" class="header header-yellow" onclick="showNextElement(this)">
            Extra
        </div>
        <div id="extra" class="content" style="display:none">
            {{Extra}}
        </div>
    </div>
    <br> 
    <p class="" style="margin: 5.5px;"></p>
    {{/Extra}}

    <div id="info-section">
        <div id="info-header" class="header header-blue" onclick="showNextElement(this)">
            Information
        </div>

        <div id="info" class="content" style="display:none">
            <div>
                <b>Deck</b>: <br><i>{{Deck}}</i>
            </div>

            <br>
            
            {{#Tags}}
            <div id="tags">
                <b>Tags</b>: <br><i>{{Tags}}</i>
            </div>
            {{/Tags}}
        </div>
    </div>
    <br>

    <div id="functional-elements">
        <div id="show-one-cloze-left"></div>
        <div id="show-one-cloze-right"></div>
        <div id="no-more-cloze"></div>
    </div>

</div>

</div>


<script src="_jquery.hotkeys.js"></script>
<script src="_jquery.visible.min.js"></script>

<script>
    var equals = (a, b) => {
        if (a === b) return true;
        if (a instanceof Date && b instanceof Date)
            return a.getTime() === b.getTime();
        if (!a || !b || (typeof a !== 'object' && typeof b !== 'object'))
            return a === b;
        if (a.prototype !== b.prototype) return false;
        let keys = Object.keys(a);
        if (keys.length !== Object.keys(b).length) return false;
        return keys.every(k => equals(a[k], b[k]));
    };

    var dummyClozes = document.getElementById("dummy-clozes").querySelectorAll(":scope > span")
    var clozesExist = dummyClozes[0] && dummyClozes[0].hasAttribute("cloze-id")
    if (clozesExist) {
        // normal mode
        var genuineClozeIndeces = [...dummyClozes].map(x => Number.parseInt(x.getAttribute("cloze-id").slice(1)))

        document.getElementById("enhanced-clozes").innerHTML = prepareEnhancedClozes(genuineClozeIndeces)
        var curShowIdx = 0;
    } else {
        if (equals(data['parts'], [["", null]])){
            // card designer mode
            var data = {"answers": ["cloze"], "hints": [""]} 
        } else {
            // no cloze mode
            document.getElementById("enhanced-clozes").innerHTML = prepareEnhancedClozes()
        }
    }

    $(function () {

        // INITIALIZE CLOZES
        //      genuine clozes refer to those belong to current card and need to be answered, e.g. { {c2::abc} } on card2
        //      pseudo clozes refer to the opposite, e.g. { {c1::abc} } and { {c3::abc} } on card2
        $('.genuine-cloze, .pseudo-cloze').each(function (index, elem) {
            toggleCloze(elem, 'hint')
        });

        // SCROLL TO FIRST CLOZE
        if ($('.genuine-cloze').length != 0) {
            scrollToCloze($('.genuine-cloze').first().get(0));
        }

        $(document).keyup(function (event) {
            if (event.which == 73){
                showOneCloze();
            }
            if (event.which == 188){
                showAllPseudoClozes();
            }
        })

        // this is probably needed for iOS, see here: https://stackoverflow.com/a/15096054
        $('.pseudo-cloze').css('cursor', 'pointer')
        $('.genuine-cloze').css('cursor', 'pointer')
        $('#show-one-cloze-left').css('cursor', 'pointer')
        $('#show-one-cloze-right').css('cursor', 'pointer')

        if (typeof firstTimeLoadingEnhancedCloze === 'undefined') {
            firstTimeLoadingEnhancedCloze = false

            // simply doing for example "$(.pseudo-cloze).click()" doesn't work on iOS
            $(document).on('click', '.pseudo-cloze', function (event) {
                toggleCloze(event.target, 'toggle');
            });

            $(document).on('click', '.genuine-cloze', function (event) {
                toggleCloze(event.target, 'toggle');
            });

            $(document).on('click', '#show-one-cloze-left', function (event) {
                showOneCloze();
            });

            $(document).on('click', '#show-one-cloze-right', function (event) {
                showOneCloze();
            });
        }

    });

    function prepareEnhancedClozes(genuineClozeIndeces){
        var result = "";
        var i = 0
        
        // the data variable is set by a script tag in the data field of the note
        for(var [part, clozeId] of data["parts"]){
            result += part
            if(i == data["parts"].length - 1) break

            result += genuineClozeIndeces.indexOf(clozeId) != -1 ? "genuine-cloze" : "pseudo-cloze"
            i += 1
        }
        return result
    }

    function scrollToCloze(elem) {
        $('html, body').animate({
            scrollTop: $(elem).offset().top - 60
        }, 500);
    }

    function showOneCloze() {
        gClozeExists = (index) => $('.genuine-cloze[index=' + index + ']').length != 0
        pClozeExists = (index) => $('.pseudo-cloze[index=' + index + ']').length != 0
           
        while(pClozeExists(curShowIdx)){
                curShowIdx += 1
        }
        if(!gClozeExists(curShowIdx)) {
            $('#no-more-cloze').animate({
                display: "toggle",
            }, 500);
            return
        } 

        $('.genuine-cloze[index=' + curShowIdx + ']').each(function (index, elem) {
            if (!$(elem).is(":visible")) {
                scrollToCloze(elem);
            } else {
                toggleCloze(elem, 'answer');
                if (!$(elem).is(":visible")) {
                    scrollToCloze(elem);
                } else {
                }
                $(elem).hide(0);
                $(elem).fadeIn(500);
                curShowIdx++;
            }
        })
    }

    function showAllPseudoClozes() {
        $('.pseudo-cloze').each(function (index, elem) {
            toggleCloze(elem, 'answer');
        })
    }

    function toggleCloze(elem, displayOption) {
        var index = $(elem).attr('index');
        var answer = data["answers"][index]
        var hint = data["hints"][index]

        if(answer.startsWith('#')){
            answer = answer.slice(1)

            if($(elem).attr('class') == 'pseudo-cloze'){
                $(elem).attr('show-state', 'answer');
                $(elem).html(answer);
                return
            } 
        }

        hint = '&nbsp;&nbsp;[&nbsp;&nbsp;' + hint + '&nbsp;&nbsp;]&nbsp;&nbsp;';

        if (displayOption == 'answer') {
            $(elem).attr('show-state', 'answer');
            $(elem).html(answer);
        } else if (displayOption == 'hint') {
            $(elem).attr('show-state', 'hint');
            $(elem).html(hint);
        } else if (displayOption == 'toggle') {
            if ($(elem).attr('show-state') == 'hint') {
                $(elem).attr('show-state', 'answer');
                $(elem).html(answer);
            } else {
                $(elem).attr('show-state', 'hint');
                $(elem).html(hint);
            };
        };

        // rerun mathjax on the document so that the cloze text gets formatted
        // ... for MathJax 2
        try {
            MathJax.Hub.Queue(["Typeset", MathJax.Hub]);
        } catch {}
        // ... for MathJax 3     
        try {
            MathJax.typesetPromise()
        } catch {}

    }

    function showNextElement(elem) {
        $(elem).next().show(0);
    };
</script>

**Comment by BellaMed** [comment]
<script type='text/javascript'>data={"parts": [["My name is&nbsp;<span class=\"", 1], ["\" index=\"0\" show-state=\"hint\" cloze-id=\"c1\"></span>", null]], "answers": ["bella"], "hints": [""]}</script>

**Comment by RisingOrange** [comment]
Thanks for the help!
