### ISSUE TITLE
One by one revealing during review

### ISSUE THREAD

**Issue by marcozer** [RisingOrange/anki-enhanced-cloze#22]
First of all thank you for this wonderfull addon which is a huge step beyond compared to the old version. 
The only issue I report is when revealing clozes with shortcut during review. Indeed, they won't reveal one by one but all of them after only one push.
The one by one feature works for the blue "pseudo cloze"
thanks a lot

**Comment by RisingOrange** [comment]
Thanks for the nice words!
I updated the add-on and it now only reveals one cloze at a time, even if you have multiple clozes with the same id (like {{c1::text}} {{c1::other text}}).
Does this solve the problem for you?

**Comment by marcozer** [comment]
thank you so much
