### ISSUE TITLE
enhanced Cloze on iPhone/iPad app

### ISSUE THREAD

**Issue by ivvn9** [RisingOrange/anki-enhanced-cloze#23]
when I touch each genuine cloze they all uncover.
on android its ok but on iphone/ipad all genuine cloze are uncovered.
how do I solve it?

thanks

**Comment by jaywhy** [comment]
I just want to report, that I have the same issue with the iOS version of Anki.

**Comment by ggilmore** [comment]
Hello, I am also running into this issue. I'm not familiar with Anki addon development, but is some sort of debugging information that I could provide to help solve this?

**Comment by RisingOrange** [comment]
I will look into this soon.

**Comment by RisingOrange** [comment]
There is a new update to the add-on that makes this work correctly on iOS, but you also have to change some settings in AnkiMobile. AnkiMobile has a feature called "touch actions" where actions happen when you touch certain parts of the screen while reviewing. This actions can be changed from Settings -> Reviews -> Touch. You can setup different actions for the front and back of the card. I have disabled everything, but you might leave some actions if you want to use them and it doesn't interfere with tapping the clozes. (You can also remap actions to swipe gestures)

**Comment by jaywhy** [comment]
I can confirm the latest version works on iOS. Thank you.

**Comment by ivvn9** [comment]
It still doesn't work on iPhone/ipad. I've tried to turn off the "touch screen" option and it still doesn't work. Can you put a screenshot to see how you do it?

**Comment by jaywhy** [comment]
In Settings -> Reviews -> Taps, I turned everything off.


![IMG_A2825E27C3F0-1](https://user-images.githubusercontent.com/3405/176995225-13c61d56-ca27-409b-88bc-a762eaf91afb.jpeg)

**Comment by ivvn9** [comment]
Thank you so much, i do this but it still doesn't work. It's a shame because it seems like a great complement
