### ISSUE TITLE
No-Cloze mode doesn't work on ankidroid.

### ISSUE THREAD

**Issue by gustavosmendes** [RisingOrange/anki-enhanced-cloze#24]
It shows like "there is no cloze" or empty card.

Works properly if added {{cloze::Cloze99}} in front card.

**Comment by gustavosmendes** [comment]
Just added 
<span style="display:none">{{cloze::Cloze99}}</span>

Solved it.

**Comment by RisingOrange** [comment]
Hello!
Unfortunately I don't know of any way to make it work automatically on mobile. I added information about this in the description on AnkiWeb.
