### ISSUE TITLE
Anki-enhanced-cloze addon is causing errors with the anki-enhanced-cloze card type

### ISSUE THREAD

**Issue by southsiderpgh** [RisingOrange/anki-enhanced-cloze#30]
Hi-- I'm having trouble using the card type created by the addon. I've tried toggling other addons off and on but I can't figure out if another addon is affecting the enhanced cloze card type as well. Any suggestions would be helpful, I'd really like to be able to use this addon. 

Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.7
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-03-28 13:35:51
Add-ons possibly involved: ⁨Enhanced Cloze for Anki 21⁩

**Comment by RisingOrange** [comment]
Hi! What exactly is the problem? Did you create some notes of the "Enhanced Cloze 2.1 v2" note type and do they not show up as expected?

**Comment by southsiderpgh** [comment]
Hi -- thanks for responding!

The problem is that when I try to create notes of the Enhanced Cloze 2.1 v2
note type I get the error message that I posted. Just in case it matters, I
did add a field and renamed some fields (I left the Cloze99 field alone) on
my card template.

**Comment by southsiderpgh** [comment]
I just replicated the error and found additional text, I apologize, I
didn't notice that previously.

Here you go:
Error
An error occurred. Please start Anki while holding down the shift key,
which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools >
Add-ons menu item to disable some add-ons and restart Anki, repeating until
you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please
report the issue on the add-on support site.
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.7
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-03-28 13:35:51
Add-ons possibly involved: ⁨Enhanced Cloze for Anki 21⁩

Caught exception:
Traceback (most recent call last):
  File "anki/notes.py", line 150, in _field_index
KeyError: 'Content'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "aqt/webview.py", line 541, in handler
  File "aqt/editor.py", line 528, in <lambda>
  File "aqt/notetypechooser.py", line 121, in choose_notetype
  File "aqt/notetypechooser.py", line 138, in selected_notetype_id
  File "aqt/addcards.py", line 148, in on_notetype_change
  File "decorator.py", line 232, in fun
  File "anki/hooks.py", line 89, in decorator_wrapper
  File "anki/hooks.py", line 80, in repl
  File "aqt/editor.py", line 476, in loadNote
  File "/Users/heatherhtillman/Library/Application
Support/Anki2/addons21/1990296174/enhanced_cloze.py", line 197, in
new_fields_check
    result = original_fields_check(self)
  File "anki/notes.py", line 191, in fields_check
  File "anki/notes.py", line 67, in _to_backend_note
  File "anki/hooks_gen.py", line 378, in __call__
  File "/Users/heatherhtillman/Library/Application
Support/Anki2/addons21/1990296174/enhanced_cloze.py", line 85, in
maybe_fill_in_or_remove_cloze99
    if in_use_clozes():
  File "/Users/heatherhtillman/Library/Application
Support/Anki2/addons21/1990296174/enhanced_cloze.py", line 81, in
in_use_clozes
    cloze_start_matches = re.findall(cloze_start_regex, note["Content"])
  File "anki/notes.py", line 155, in __getitem__
  File "anki/notes.py", line 152, in _field_index
KeyError: 'Content'

**Comment by RisingOrange** [comment]
It seems that you removed the "Content" field or renamed it. The add-on needs this field and I think it will work again when you add it back in.

You can reset the note type to its default form at any time (main Anki window -> Tools -> "Reset Enhanced Cloze note type to default").

You can remove or rename all fields except for Content and Cloze99. If you remove/rename fields you probably also want to remove/rename these fields in the card template because else they will show up during review.

**Comment by southsiderpgh** [comment]
Thanks so much for taking the time to help! I'm happily using the addon
now. 🌻
