### ISSUE TITLE
Showing pseudoclozes

### ISSUE THREAD

**Issue by Becogu** [RisingOrange/anki-enhanced-cloze#31]
Thanks for the great work, I´ve been enjoying this addon for weeks and it´s awesome.
I was wondering if there was a way so that pseudoclozes would be shown revealed automatically instead of having to enter "shift+n".
Thank you so much!

**Comment by RisingOrange** [comment]
I'm glad you like the add-on!

This is already possible, this is from the add-ons description on AnkiWeb:

"Normal" clozes
If you want a cloze to alway be displayed when it's a pseudo cloze, prepend the answer with a #-sign like this: {{c1::#some text}}.
