### ISSUE TITLE
Edit field during Review (Cloze)

### ISSUE THREAD

**Issue by spirla** [RisingOrange/anki-enhanced-cloze#32]
Please fix incompatibility with "Edit field during review (Cloze)".
Otherwise, it is very difficult to create the clozes from imported plain texts.
As it is you have to edit one by one in the editor.

Thanks!

**Comment by RisingOrange** [comment]
I added support for "Edit field during review (cloze)" to the newest version of the add-on!

**Comment by spirla** [comment]
Hi very good job.
Thanks. I wasn't being able to use the edit, but I updated the other addons and it worked.
Bought you a coffee, but the comunity value is priceless.

Best regards

**Comment by RisingOrange** [comment]
Thanks! I am glad it works for you now.
