### ISSUE TITLE
Cloze extra fields

### ISSUE THREAD

**Issue by amon-666** [RisingOrange/anki-enhanced-cloze#36]
Hi,

Sometimes I make cloze cards with 2-10 different clozes (c1, c2, c3...), which creates 10 cards off of one note. sometimes I want to make one or more cards have *seperate* extra fields. That way I can add in an image or some text that only appears on card 2 (cloze 2). I have researched for probably 30-60 minutes on this issue and could find no easy solution. I am aware that it is possible to suspend the card, copy all of the text, and make a seperate note for the cloze.

Is there a better solution?

Thanks for your assistance.

**Comment by RisingOrange** [comment]
This can be done using this feature of Anki:
https://docs.ankiweb.net/templates/generation.html?highlight=conditional#cloze-templates

I currently have no plans to add this to the Enhanced Cloze note type but if you want I can help you make a note type that works as you described it.
