### ISSUE TITLE
only 1 cloze show

### ISSUE THREAD

**Issue by coolbeanz10101010** [RisingOrange/anki-enhanced-cloze#40]
How can I edit to have only 1 cloze type hidden each time and not all of them??

**Comment by RisingOrange** [comment]
> "Normal" clozes:
If you want a cloze to alway be displayed when it's a pseudo cloze, prepend the answer with a #-sign like this: {{c1::#some text}}.

So if you want to to only show one cloze at a time you would have to add the "#" to every cloze on the note.

Hope this helps.

**Comment by mendes115** [comment]
Is there any other way other than adding the "#"? Maybe something you can change directly in the card settings?

**Comment by RisingOrange** [comment]
I just updated the add-on and added the `revealPseudoClozesByDefault` option. When you set it to "true" you will get the behavior you want. 

You can reach the screen where you can edit the options like this: Tools -> Manage note types -> Enhanced Cloze 2.1 v2 -> Cards. (The `revealPseudoClozesByDefault` option is not on the image yet.)
![image](https://user-images.githubusercontent.com/31575114/179310340-315175eb-f307-4224-aa13-e2c420cc7202.png)

If you want you can have two copies of the note type, one with the option set to true and one with the option set to false. Only the note type named "Enhanced Cloze 2.1 v2" will receive updates though.

Does this solve your problem?

**Comment by mendes115** [comment]
Sadly it didn't´work. I updated the version, but in there card settings there was no revealPseudoClozesByDefault option, so I added it underneath the var underlineRevealedGenuineClozes line and set it to true, but it still doesn't work. :(

**Comment by RisingOrange** [comment]
Try this:
- Check for add-on updates (Tools -> Add-ons -> Check for Updates)
- Make sure the add-on is not disabled (under Tools -> Add-ons)
- Restart Anki
- Now the new option should be present and work

If that doesn't work try Tools -> Reset Enhanced Cloze note type to default

**Comment by mendes115** [comment]
Yes, now it is shown in the card styling, but after setting it to true, the first letter of each cloze content disappears...
<img width="1182" alt="Bildschirmfoto 2022-07-16 um 17 14 40" src="https://user-images.githubusercontent.com/109386201/179360925-1fafdd96-1e9c-4536-90b7-442a624221c4.png">
<img width="1182" alt="Bildschirmfoto 2022-07-16 um 17 14 52" src="https://user-images.githubusercontent.com/109386201/179360930-b6910fed-f631-4c8c-b2c3-c332fbf07c64.png">
<img width="1182" alt="Bildschirmfoto 2022-07-16 um 17 14 57" src="https://user-images.githubusercontent.com/109386201/179360931-fd03481b-9084-4dbd-b005-2e3e566c6b91.png">

**Comment by RisingOrange** [comment]
My bad. Uploaded a new version of the add-on that fixes this.

**Comment by mendes115** [comment]
Yes, it´s fixed! Now it works perfectly - thanks a lot!! Saved my day! 🤗

**Comment by RisingOrange** [comment]
Great!
