### ISSUE TITLE
NEW UPDATE MADE THE EXTENSION STOP WORKING

### ISSUE THREAD

**Issue by dpl366** [RisingOrange/anki-enhanced-cloze#41]
I JUST UPTATED THE ANKI ENHANCED CLOZE TODAY AND  MY CARDS STOP HIDING WORDS, I AM DESPERATE 90% OF MY CARDS HAVE THIS EXTENSION PLEASE HELP ME FIX THIS

![5b25a068-9473-4a3a-9183-10abceb1baba](https://user-images.githubusercontent.com/109423046/179357214-5095604c-d137-4084-9cd3-d69746dbda4b.jpg)

![image](https://user-images.githubusercontent.com/109423046/179357223-6007a9dc-773e-441c-955d-a9fbdcc29517.png)

**Comment by RisingOrange** [comment]
Don't worry, I'll help you fix this. 

First on the main Anki window click Tools  and then "Reset Enhanced Cloze note type".

**Comment by RisingOrange** [comment]
If that doesn't work can you please send a screenshot how the cards look like?

**Comment by dpl366** [comment]
brooooooooooo, thanks a lot! it worked
