### ISSUE TITLE
reset css option should ask user first

### ISSUE THREAD

**Issue by ijgnd** [RisingOrange/anki-enhanced-cloze#42]
For the option "Reset Enhanced Cloze note type to default" you use askUser to confirm, see [here](https://github.com/RisingOrange/anki-enhanced-cloze/blob/b818fe0c7e24ce3b4836963803bd1d59074026a9/src/enhance-cloze/enhanced_cloze.py#L119). 

For the option "Reset Enhanced Cloze css to default" there's no such question asked.

I think there should also be a confirmation to avoid accidental deletions.

**Comment by RisingOrange** [comment]
Added in c21b68f94a6f3f3edff2ebd0a30b60500dcb2fd0.
