### ISSUE TITLE
put reset options maybe under one parent menu?

### ISSUE THREAD

**Issue by ijgnd** [RisingOrange/anki-enhanced-cloze#43]
that's just a personal preference but I think a submenu like "Enhanced Cloze" that has the entries "Reset note type to default" and  "Reset css to default" would be better.

This has two advantages: When starting to read from the left you see directly the add-on name whereas when reading "Reset ..." I always hestitate. Also since a lot of add-ons add entries into the tools menu even one entry less helps.

Thanks for basically re-creating this add-on.

**Comment by RisingOrange** [comment]
Thanks for the feedback and creating many great add-ons!

Added this to the newest version of the add-on as well as your other suggestion.
