### ISSUE TITLE
Turn Add-on completely off

### ISSUE THREAD

**Issue by marinafrayb** [RisingOrange/anki-enhanced-cloze#48]
Hello, I have the Anking step deck and am not sure how to turn this feature off. I am relatively new to anki and am hoping to just have all the clozes showing for now. Thank you for your help!

**Comment by RisingOrange** [comment]
AnKing decks don't use the Enhanced Cloze note type, so this probably doesn't have to do with the add-on.

Could you post a picture of a note in the deck where you want the clozes to be all shown from the beginning?

**Comment by marinafrayb** [comment]
![Screen Shot 2022-09-07 at 12 41 33 PM](https://user-images.githubusercontent.com/112649956/188933532-f410a8d1-e8b9-41da-9c3f-466e239558cd.png)
![Screen Shot 2022-09-07 at 12 46 47 PM](https://user-images.githubusercontent.com/112649956/188934530-a016a3e5-ccff-440a-ba9b-5b8d1b614c71.png)
![Screen Shot 2022-09-07 at 12 48 59 PM](https://user-images.githubusercontent.com/112649956/188934879-eba462f7-e468-4828-8b29-cb0e2b6ca668.png)

Oh I'm sorry then, I'm not sure what exactly I updated or changed but I would just like everything revealed (no crown symbol) and all clozes separate the way it was before.

**Comment by marinafrayb** [comment]
I think it is just the AnKing note type that is causing this but not sure how to change it

**Comment by RisingOrange** [comment]
Some AnKing note types have a field named "One by one". It's the last field. When you have something in there, these crowns show up on the back side of the card. You just have to delete everything in this field.

**Comment by RisingOrange** [comment]
@marinafrayb
