### ISSUE TITLE
is it possible to change the font to Arial?

### ISSUE THREAD

**Issue by synog** [RisingOrange/anki-enhanced-cloze#49]
Hello Community,

is it possible to change the font to Arial? I see the cards only with Times New Roman.

Greetings
synog

**Comment by sylvialinyz** [comment]
1. go to "manage card type(ctrl+shift+M)", 
2. then choose your card style "enhanced cloze(for anki 2.1)
3. click "card" on the right,
4. choose "styling", type"font" the search box then you can locate the code, change the font name to "Arial", 
5. save it and it's done.
