### ISSUE TITLE
Disable "write the answer"

### ISSUE THREAD

**Issue by Acuelatus** [RisingOrange/anki-enhanced-cloze#5]
In the Anki version for iPad every time i review a card with the card template enhanced-cloze it asks me to "write the answer", while in the desktop version this does not happen. Is there a way to disable "write the answer"?

![IMG_5274F4AE5896-1](https://user-images.githubusercontent.com/70332135/129345637-970abef2-5f84-46a8-b344-a946876cbf9c.jpeg)

<img width="1387" alt="Captura de pantalla 2021-08-13 a las 12 44 27 p  m" src="https://user-images.githubusercontent.com/70332135/129345726-fc41e992-ed52-4983-8585-c0bdbb763636.png">

**Comment by RisingOrange** [comment]
I just uploaded an update that should fix this.
