### ISSUE TITLE
No-cloze mode doesn't not work on mobile - ankidroid

### ISSUE THREAD

**Issue by gustavosmendes** [RisingOrange/anki-enhanced-cloze#6]
Hi,

again, thank you for all your work. 

the main problem is it showing as an empty cloze on mobile. It works fine on computer 

Thank you.

**Comment by gustavosmendes** [comment]
The problem is solved if i add any {{c1::}} to the cloze 1 field, e.g.

**Comment by gustavosmendes** [comment]
Fixed adding css:

{{cloze::Cloze99}} in frontside after <#note>. It is simple, but effective. 

<div>
    
    {{#Note}}
    <div id="note-section">
        <div id="note-header" class="header header-red" onclick="showNextElement(this)">
            Note
        </div>
        <div id="note" class="content" style="display:none">
            {{Note}}
        </div>
    </div>
    <p class="" style="margin: 3px;"></p>
    {{/Note}}


<div display= "none>{{cloze:Cloze99}}</div>

**Comment by gustavosmendes** [comment]
Aparently, i've created a bigger problem with other c2 and c3 on cloze models.

**Comment by gustavosmendes** [comment]
I think the solution would be: if a card is "Enhanced Cloze 1", then show cloze99 as none, since cloze99 is an empty cloze - "no cloze model. If Enhanced Cloze is N, then don't add this to card.
The problem is I don't how write this code and even don't know if it is possible to do this.

**Comment by RisingOrange** [comment]
I've uploaded an update to Ankiweb that should solve this. You have to do a force collection sync from your desktop to your phone for it to work (the notetype doesn't get updated without this). So you have to install the update for the add-on, restart Anki and then do a force sync.
