### ISSUE TITLE
Conflict with Popup Dictionary 

### ISSUE THREAD

**Issue by gustavosmendes** [RisingOrange/anki-enhanced-cloze#7]
"There is a conflict with Popup Dictionary. The conflict is the "<script src="_jquery-3.2.1.min.js"> <script>" write in note "Enhanced Cloze 2.1 v2". Can I remove it manually, or it is fundamental to keep Enhanced Cloze (for Anki 2.1) working?

Thanks."

Not mine, just reporting.

If your rename _jquery-3.2.1.min.js to _jquery.3.2.1.min.js(in every source), both addons works with no conflict.

**Comment by gustavosmendes** [comment]
Deleted <script _jquery...> and used _jquery.visible as call " # front template:
        # ... replace the script part"
      No conflicts, even with ankiwebview.

**Comment by RisingOrange** [comment]
I'm glad you found a solution. I will edit the add-on.

**Comment by gustavosmendes** [comment]
enhanced.py
>         script_re = '<script src="_jquery.hotkeys.js"></script>[\w\W]+$'
>         with open(front_path) as f:
>             front = f.read()
>         script = re.search(script_re, front).group(0)
>         cur_front = re.sub(script_re, script, cur_front)
>         model["tmpls"][0]["qfmt"] = cur_front
        and
for html front template
>        <div id="show-all-pseudo-clozes"></div>
>     </div>
> 
> </div>
> 
> </div>
> 
> <script src="_jquery.hotkeys.js"></script>
> <script src="_jquery.visible.min.js"></script>
> 
> 
> <script>
        
       I don't see any need to load jquery 3.2.1, since anki use 3.6.0. 
       The conflict is due loading 3 jquery lib, i think - again, as you know, I don't understand so much about coding.

**Comment by RisingOrange** [comment]
The updated version is now on Ankiweb. Thanks for the help!
