### ISSUE TITLE
 After update 27/08, hotkeys (enter, space, j, n, 1,2,3,4) don't reveal clozes, It only reveals if you click on it

### ISSUE THREAD

**Issue by PnDlKalpus** [RisingOrange/anki-enhanced-cloze#77]
Boa noite meus amigos!!

Problema: após a última atualização, as teclas de atalho não revelam os clozes... Teclas como ENTER, ESPAÇO, 1, 2, 3, 4 não revelam os clozes. O único jeito para revelar é clicando em cima.

**Comment by PnDlKalpus** [comment]
Good night my friends!!

Problem: After the last update, hotkeys don't reveal the clozes... Keys like ENTER, SPACE, 1, 2, 3, 4 don't reveal the clozes. The only way to reveal it is to click on it.

EDIT1: Just like the J, N keys don't reveal the Clozes.

**Comment by RisingOrange** [comment]
Try resetting the note type. (Anki's main window -> Tools -> Enhanced Cloze -> Reset Enhanced Cloze note type)

Then you can go into the config for the note type (Anki's main window -> Tools -> Enhanced Cloze -> Config) and change the shortcut for revealing clozes if you want.

**Comment by PnDlKalpus** [comment]
Eu já tinha feito isso e não resolveu. No entanto, com essa nova atualização de 10/09 Enhanced cloze, voltou a funcionar novamente, tudo certo meu amigo!!! Obrigado pela atenção!! você é incrível!!

**Comment by RisingOrange** [comment]
I'm glad the update helped!
